// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEXQjVBnN7t_7hodglmLGJjR5PG5ZRLfY',
    appId: '1:1072991154998:web:9e7c99e71c430c2ee17997',
    messagingSenderId: '1072991154998',
    projectId: 'smart-grocery-293c0',
    authDomain: 'smart-grocery-293c0.firebaseapp.com',
    storageBucket: 'smart-grocery-293c0.firebasestorage.smart_grocery',
    measurementId: 'G-KPJ2X5C617',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpbUWtaXAr-0CjkiOqfvXhYluLxMUBQKU',
    appId: '1:1072991154998:android:8191e3a346269ec0e17997',
    messagingSenderId: '1072991154998',
    projectId: 'smart-grocery-293c0',
    storageBucket: 'smart-grocery-293c0.firebasestorage.smart_grocery',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWYJXxxrEnBOw5pVW38F1X0mQt7l7P8gE',
    appId: '1:1072991154998:ios:c37c7d141d20b9e3e17997',
    messagingSenderId: '1072991154998',
    projectId: 'smart-grocery-293c0',
    storageBucket: 'smart-grocery-293c0.firebasestorage.smart_grocery',
    iosBundleId: 'com.example.smartGrocery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWYJXxxrEnBOw5pVW38F1X0mQt7l7P8gE',
    appId: '1:1072991154998:ios:c37c7d141d20b9e3e17997',
    messagingSenderId: '1072991154998',
    projectId: 'smart-grocery-293c0',
    storageBucket: 'smart-grocery-293c0.firebasestorage.smart_grocery',
    iosBundleId: 'com.example.smartGrocery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEXQjVBnN7t_7hodglmLGJjR5PG5ZRLfY',
    appId: '1:1072991154998:web:ec152954e093f519e17997',
    messagingSenderId: '1072991154998',
    projectId: 'smart-grocery-293c0',
    authDomain: 'smart-grocery-293c0.firebaseapp.com',
    storageBucket: 'smart-grocery-293c0.firebasestorage.smart_grocery',
    measurementId: 'G-H7KR1S42CT',
  );
}